-- ============================================================
-- PEDEAI — TABELA: mensagens
-- ============================================================
-- Armazena todas as mensagens trocadas entre clientes e a IA.
-- A Evolution Go não tem endpoint de histórico, então persistimos aqui.
-- Executar no SQL Editor do Dashboard do Supabase.
-- ============================================================

CREATE TABLE IF NOT EXISTS mensagens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    restaurante_id  UUID REFERENCES "Restaurantes"("id") ON DELETE CASCADE,
    
    telefone        TEXT NOT NULL,
    nome_contato    TEXT,
    conteudo        TEXT NOT NULL,
    tipo            TEXT DEFAULT 'text',
    direcao         TEXT NOT NULL CHECK (direcao IN ('recebida', 'enviada')),
    
    message_id      TEXT,
    metadata        JSONB
);

COMMENT ON TABLE mensagens IS 'Histórico de mensagens WhatsApp — persistido via webhook da Evolution Go';
COMMENT ON COLUMN mensagens.telefone IS 'Telefone do cliente com DDD (ex: 5533987140460)';
COMMENT ON COLUMN mensagens.direcao IS 'recebida = cliente enviou | enviada = IA respondeu';
COMMENT ON COLUMN mensagens.message_id IS 'ID original da Evolution Go para evitar duplicatas';
COMMENT ON COLUMN mensagens.tipo IS 'text, audio, image';

-- Índices
CREATE INDEX IF NOT EXISTS idx_mensagens_restaurante ON mensagens(restaurante_id);
CREATE INDEX IF NOT EXISTS idx_mensagens_telefone ON mensagens(telefone);
CREATE INDEX IF NOT EXISTS idx_mensagens_created_at ON mensagens(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mensagens_message_id ON mensagens(message_id);
CREATE INDEX IF NOT EXISTS idx_mensagens_telefone_restaurante ON mensagens(telefone, restaurante_id);

-- RLS
ALTER TABLE mensagens ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on mensagens" ON mensagens FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Realtime (para atualização instantânea no frontend)
DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE mensagens;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- FIM — Agora execute este script no SQL Editor do Supabase
-- ============================================================
