-- ============================================================
-- PEDEAI — SCRIPT COMPLETO DE CRIAÇÃO DO BANCO DE DADOS
-- ============================================================
-- Supabase (PostgreSQL)
-- Executar no SQL Editor do Dashboard do Supabase
-- Última atualização: 2026-07-07
-- ============================================================


-- ============================================================
-- 0. EXTENSÕES
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ============================================================
-- 1. TABELA: admin_acessos
-- ============================================================
-- Credenciais de acesso ao painel administrativo (/admin/login).
-- Usado para gerenciar restaurantes, visualizar métricas globais, etc.

CREATE TABLE IF NOT EXISTS admin_acessos (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    "email"       TEXT UNIQUE,
    "senha"       TEXT
);

COMMENT ON TABLE admin_acessos IS 'Credenciais de acesso ao painel admin do PedeAi (/admin)';

-- ⚡ ADMIN PADRÃO — TROQUE A SENHA APÓS O PRIMEIRO ACESSO!
INSERT INTO admin_acessos (email, senha)
VALUES ('admin@pedeai.com', 'admin123')
ON CONFLICT (email) DO NOTHING;


-- ============================================================
-- 1. TABELA: Restaurantes
-- ============================================================
-- Armazena os dados de cada restaurante cadastrado no sistema.
-- É a tabela central — quase todas as outras referenciam ela.

CREATE TABLE IF NOT EXISTS "Restaurantes" (
    "id"                     UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created_at"             TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Dados básicos
    "nome"                   TEXT,
    "email"                  TEXT UNIQUE,
    "senha"                  TEXT,
    "telefone"               TEXT,             -- Telefone do restaurante (contato comercial)
    "telefone_dono"          TEXT,             -- Telefone do dono (usado pelo n8n para alertas de estoque)
    
    -- Mesas
    "quantidade_mesas"       TEXT,             -- Quantidade de mesas ativas
    "quantidade_max_mesas"   TEXT,             -- Limite máximo de mesas (plano)
    "max_mesas"              TEXT,             -- Alias usado pelo frontend (mesmo que quantidade_max_mesas)
    
    -- Horários de funcionamento
    "horario_abertura"       TEXT,
    "horario_fechamento"     TEXT,
    "horario_fecha_cozinha"  TEXT,
    
    -- Configurações do sistema
    "fechar_mesa_auto"       BOOLEAN DEFAULT TRUE,      -- Fechar mesa automaticamente após pagamento
    "alertas_piscantes"      BOOLEAN DEFAULT TRUE,      -- Alertas visuais piscantes na tela
    "sons_habilitados"       BOOLEAN DEFAULT TRUE,      -- Sons de notificação
    "impressao_auto"         BOOLEAN DEFAULT FALSE,     -- Impressão automática de pedidos
    "gerencia_estoque"       BOOLEAN DEFAULT TRUE,      -- Habilitar controle de estoque
    "modo_cobranca"          TEXT DEFAULT 'mesa',       -- 'mesa' (conta única) ou 'comanda' (conta por check-in)
    
    -- Estoque — limites de alerta
    "alerta_estoque_baixo"   INTEGER DEFAULT 15,        -- Alerta amarelo (estoque baixo)
    "alerta_estoque_critico" INTEGER DEFAULT 5,         -- Alerta vermelho (estoque crítico)
    
    -- Financeiro
    "taxa_servico"           NUMERIC DEFAULT 0          -- Taxa de serviço (%) aplicada na conta
);

COMMENT ON TABLE "Restaurantes" IS 'Cadastro de restaurantes do sistema PedeAi';
COMMENT ON COLUMN "Restaurantes"."telefone_dono" IS 'Telefone do dono — recebe alertas de estoque via WhatsApp (n8n)';
COMMENT ON COLUMN "Restaurantes"."taxa_servico" IS 'Percentual da taxa de serviço aplicada ao fechar a conta';
COMMENT ON COLUMN "Restaurantes"."gerencia_estoque" IS 'Se TRUE, o sistema desconta estoque automaticamente a cada pedido';


-- ============================================================
-- 2. TABELA: Produtos
-- ============================================================
-- Cardápio de cada restaurante. Cada produto pertence a um restaurante.
-- A IA consulta esta tabela via tool "Produtos_cardapio" no n8n.

CREATE TABLE IF NOT EXISTS "Produtos" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    "restaurante_id"  UUID REFERENCES "Restaurantes"("id") ON DELETE CASCADE,
    
    -- Dados do produto
    "nome"            TEXT,
    "preco"           TEXT,                  -- Preço armazenado como texto (ex: "25.90")
    "categoria"       TEXT,                  -- Ex: "Bebidas", "Porções", "Pratos", "Sobremesas"
    "estacao"         TEXT,                  -- Ex: "Cozinha", "Bar" — define para onde vai o pedido
    "descricao"       TEXT,                  -- Descrição ou ingredientes do produto
    
    -- Estoque
    "estoque"         INTEGER DEFAULT 0,     -- Quantidade atual em estoque
    "estoque_minimo"  INTEGER DEFAULT 10,    -- Alerta quando estoque cair abaixo deste valor
    
    -- Status
    "ativo"           BOOLEAN DEFAULT TRUE   -- Se FALSE, o produto não aparece no cardápio
);

COMMENT ON TABLE "Produtos" IS 'Cardápio de produtos de cada restaurante';
COMMENT ON COLUMN "Produtos"."estacao" IS 'Estação de preparo: Cozinha ou Bar — direciona o pedido na tela';
COMMENT ON COLUMN "Produtos"."preco" IS 'Armazenado como TEXT por compatibilidade com o frontend';


-- ============================================================
-- 3. TABELA: Pedidos
-- ============================================================
-- Cada item pedido pelo cliente via WhatsApp (IA) ou pelo sistema.
-- A IA cria pedidos via tool "Criar_pedido" no n8n.
-- 
-- Status possíveis:
--   pendente → preparando → pronto → entregue → fechado
--   pagamento_pendente (conta solicitada)
--   garcom_chamado

CREATE TABLE IF NOT EXISTS "Pedidos" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"         TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    "restaurante_id"     UUID REFERENCES "Restaurantes"("id") ON DELETE CASCADE,
    
    -- Dados do pedido
    "mesa"               TEXT,               -- Número da mesa (ex: "1", "12")
    "itens"              TEXT,               -- Nome do item pedido (ex: "Skol 600ml")
    "quantidade"         TEXT,               -- Quantidade pedida (ex: "2")
    "Subtotal"           TEXT,               -- Valor subtotal do pedido (ex: "25.80")
    "descricao"          TEXT,               -- Detalhes extras (ex: "Copos: 3", "Sem cebola")
    "status"             TEXT,               -- Status atual do pedido
    
    -- Dados do cliente
    "usuario_telefone"   TEXT                -- Telefone do cliente que fez o pedido via WhatsApp
);

COMMENT ON TABLE "Pedidos" IS 'Pedidos feitos pelos clientes via WhatsApp (IA) ou sistema';
COMMENT ON COLUMN "Pedidos"."status" IS 'Fluxo: pendente → preparando → pronto → entregue → fechado | pagamento_pendente | garcom_chamado';
COMMENT ON COLUMN "Pedidos"."usuario_telefone" IS 'Telefone do cliente que fez o pedido — inserido pela IA do n8n';


-- ============================================================
-- 4. TABELA: Usuários (Clientes)
-- ============================================================
-- Clientes que fizeram check-in ou interagiram via WhatsApp.
-- A IA cria/consulta usuários para vincular pedidos à mesa.

CREATE TABLE IF NOT EXISTS "Usuários" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"         TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    "id_restaurante"     UUID REFERENCES "Restaurantes"("id") ON DELETE SET NULL,
    
    -- Dados do cliente
    "nome"               TEXT,
    "telefone"           TEXT,               -- Telefone com DDD (ex: "5531999999999")
    "mesa_atual"         TEXT,               -- Mesa em que o cliente está sentado
    "quantas_vezes_foi"  TEXT DEFAULT '0',   -- Contador de visitas
    "Status"             TEXT DEFAULT 'Ativo', -- Status do atendimento (Ativo/Inativo)
    "ultimo_checkin"     TIMESTAMPTZ         -- Timestamp do último check-in (para detecção de mesa ocupada)
);

COMMENT ON TABLE "Usuários" IS 'Clientes que interagiram com o sistema via WhatsApp';
COMMENT ON COLUMN "Usuários"."quantas_vezes_foi" IS 'Contador de visitas — usado pela IA para personalizar saudação';
COMMENT ON COLUMN "Usuários"."Status" IS 'Status do atendimento: Ativo (na mesa) ou Inativo (saiu)';


-- ============================================================
-- 5. TABELA: estoque_restaurantes
-- ============================================================
-- Tabela auxiliar para controle de estoque sincronizada com Produtos.
-- Os triggers mantêm Produtos.estoque ↔ estoque_restaurantes.quantidade_atual em sync.

CREATE TABLE IF NOT EXISTS estoque_restaurantes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id        BIGINT UNIQUE NOT NULL,    -- FK para Produtos.id
    restaurante_id    UUID NOT NULL,              -- FK para Restaurantes.id
    quantidade_atual  TEXT DEFAULT '0',           -- Quantidade atual (texto por compatibilidade)
    created_at        TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

COMMENT ON TABLE estoque_restaurantes IS 'Espelho de estoque dos produtos — sincronizado bidireccionalmente via triggers';


-- ============================================================
-- 6. TABELA: system_logs
-- ============================================================
-- Logs do sistema para monitoramento e debugging.

CREATE TABLE IF NOT EXISTS system_logs (
    id              SERIAL PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    level           TEXT NOT NULL CHECK (level IN ('error', 'warning', 'info', 'success')),
    category        TEXT NOT NULL CHECK (category IN ('auth', 'order', 'payment', 'system', 'database', 'product', 'user')),
    message         TEXT NOT NULL,
    details         JSONB,
    restaurant_id   TEXT,
    user_agent      TEXT,
    ip_address      TEXT
);

COMMENT ON TABLE system_logs IS 'Logs do sistema para monitoramento e debugging';


-- ============================================================
-- 6b. TABELA: mensagens
-- ============================================================
-- Histórico de mensagens WhatsApp persistido pelo webhook da Evolution Go.
-- A Evolution Go não tem endpoint de histórico, então salvamos aqui.

CREATE TABLE IF NOT EXISTS mensagens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    restaurante_id  UUID REFERENCES "Restaurantes"("id") ON DELETE CASCADE,
    
    telefone        TEXT NOT NULL,              -- Telefone do cliente (ex: "5533987140460")
    nome_contato    TEXT,                       -- PushName do WhatsApp
    conteudo        TEXT NOT NULL,              -- Texto da mensagem
    tipo            TEXT DEFAULT 'text',        -- text, audio, image
    direcao         TEXT NOT NULL CHECK (direcao IN ('recebida', 'enviada')),
    
    message_id      TEXT,                       -- ID original da Evolution Go
    metadata        JSONB                       -- Dados extras
);

COMMENT ON TABLE mensagens IS 'Histórico de mensagens WhatsApp — persistido via webhook da Evolution Go';
COMMENT ON COLUMN mensagens.telefone IS 'Telefone do cliente com DDD (ex: 5533987140460)';
COMMENT ON COLUMN mensagens.direcao IS 'recebida = cliente enviou | enviada = IA respondeu';
COMMENT ON COLUMN mensagens.message_id IS 'ID original da Evolution Go para evitar duplicatas';


-- ============================================================
-- 7. ÍNDICES
-- ============================================================

-- Produtos
CREATE INDEX IF NOT EXISTS idx_produtos_restaurante ON "Produtos"("restaurante_id");
CREATE INDEX IF NOT EXISTS idx_produtos_categoria ON "Produtos"("categoria");
CREATE INDEX IF NOT EXISTS idx_produtos_ativo ON "Produtos"("ativo");

-- Pedidos
CREATE INDEX IF NOT EXISTS idx_pedidos_restaurante ON "Pedidos"("restaurante_id");
CREATE INDEX IF NOT EXISTS idx_pedidos_mesa ON "Pedidos"("mesa");
CREATE INDEX IF NOT EXISTS idx_pedidos_status ON "Pedidos"("status");
CREATE INDEX IF NOT EXISTS idx_pedidos_created_at ON "Pedidos"("created_at" DESC);
CREATE INDEX IF NOT EXISTS idx_pedidos_usuario_telefone ON "Pedidos"("usuario_telefone");

-- Usuários
CREATE INDEX IF NOT EXISTS idx_usuarios_telefone ON "Usuários"("telefone");
CREATE INDEX IF NOT EXISTS idx_usuarios_restaurante ON "Usuários"("id_restaurante");
CREATE INDEX IF NOT EXISTS idx_usuarios_mesa ON "Usuários"("mesa_atual");

-- Estoque
CREATE INDEX IF NOT EXISTS idx_estoque_produto ON estoque_restaurantes(produto_id);
CREATE INDEX IF NOT EXISTS idx_estoque_restaurante ON estoque_restaurantes(restaurante_id);

-- System Logs
CREATE INDEX IF NOT EXISTS idx_system_logs_created_at ON system_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_logs_level ON system_logs(level);
CREATE INDEX IF NOT EXISTS idx_system_logs_category ON system_logs(category);
CREATE INDEX IF NOT EXISTS idx_system_logs_restaurant_id ON system_logs(restaurant_id);

-- Mensagens
CREATE INDEX IF NOT EXISTS idx_mensagens_restaurante ON mensagens(restaurante_id);
CREATE INDEX IF NOT EXISTS idx_mensagens_telefone ON mensagens(telefone);
CREATE INDEX IF NOT EXISTS idx_mensagens_created_at ON mensagens(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mensagens_message_id ON mensagens(message_id);
CREATE INDEX IF NOT EXISTS idx_mensagens_telefone_restaurante ON mensagens(telefone, restaurante_id);


-- ============================================================
-- 8. TRIGGERS — SINCRONIZAÇÃO DE ESTOQUE
-- ============================================================

-- 8.1 Trigger: Quando INSERE um produto → cria registro no estoque
CREATE OR REPLACE FUNCTION public.sync_product_to_stock_insert()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.estoque_restaurantes (produto_id, restaurante_id, quantidade_atual)
    VALUES (NEW.id, NEW.restaurante_id, COALESCE(NEW.estoque::text, '0'))
    ON CONFLICT (produto_id) DO UPDATE
    SET quantidade_atual = EXCLUDED.quantidade_atual;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_product_insert ON public."Produtos";
CREATE TRIGGER trg_sync_product_insert
AFTER INSERT ON public."Produtos"
FOR EACH ROW
EXECUTE FUNCTION public.sync_product_to_stock_insert();


-- 8.2 Trigger: Quando ATUALIZA estoque em Produtos → sincroniza estoque_restaurantes
CREATE OR REPLACE FUNCTION public.sync_product_to_stock_update()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.estoque IS DISTINCT FROM NEW.estoque THEN
        UPDATE public.estoque_restaurantes
        SET quantidade_atual = NEW.estoque::text
        WHERE produto_id = NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_product_update ON public."Produtos";
CREATE TRIGGER trg_sync_product_update
AFTER UPDATE ON public."Produtos"
FOR EACH ROW
EXECUTE FUNCTION public.sync_product_to_stock_update();


-- 8.3 Trigger: Quando ATUALIZA estoque_restaurantes → sincroniza Produtos (reverso)
CREATE OR REPLACE FUNCTION public.sync_stock_to_product_update()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public."Produtos"
    SET estoque = CAST(NEW.quantidade_atual AS INTEGER)
    WHERE id = NEW.produto_id
      AND estoque IS DISTINCT FROM CAST(NEW.quantidade_atual AS INTEGER);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_stock_update ON public.estoque_restaurantes;
CREATE TRIGGER trg_sync_stock_update
AFTER UPDATE ON public.estoque_restaurantes
FOR EACH ROW
EXECUTE FUNCTION public.sync_stock_to_product_update();


-- 8.4 Trigger: Quando INSERE um pedido → baixa estoque automaticamente
CREATE OR REPLACE FUNCTION public.baixar_estoque_pedido_v3()
RETURNS TRIGGER AS $$
DECLARE
    item_nome TEXT;
    item_lista TEXT[];
BEGIN
    IF NEW.itens IS NULL OR NEW.itens = '' THEN
        RETURN NEW;
    END IF;

    item_lista := string_to_array(NEW.itens, ',');

    FOREACH item_nome IN ARRAY item_lista LOOP
        UPDATE public.estoque_restaurantes er
        SET quantidade_atual = (CAST(er.quantidade_atual AS INTEGER) - 1)::text
        FROM public."Produtos" p
        WHERE p.id = er.produto_id
          AND TRIM(p.nome) = TRIM(item_nome)
          AND p.restaurante_id = NEW.restaurante_id
          AND CAST(er.quantidade_atual AS INTEGER) > 0;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_baixar_estoque_on_pedido ON public."Pedidos";
CREATE TRIGGER trg_baixar_estoque_on_pedido
AFTER INSERT ON public."Pedidos"
FOR EACH ROW
EXECUTE FUNCTION public.baixar_estoque_pedido_v3();


-- ============================================================
-- 9. ROW LEVEL SECURITY (RLS)
-- ============================================================

-- System Logs
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow insert logs" ON system_logs FOR INSERT WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY "Allow read all logs" ON system_logs FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Restaurantes
ALTER TABLE "Restaurantes" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on Restaurantes" ON "Restaurantes" FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Produtos
ALTER TABLE "Produtos" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on Produtos" ON "Produtos" FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Pedidos
ALTER TABLE "Pedidos" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on Pedidos" ON "Pedidos" FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Usuários
ALTER TABLE "Usuários" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on Usuarios" ON "Usuários" FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Estoque
ALTER TABLE estoque_restaurantes ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on estoque" ON estoque_restaurantes FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Admin Acessos
ALTER TABLE admin_acessos ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on admin_acessos" ON admin_acessos FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Mensagens
ALTER TABLE mensagens ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on mensagens" ON mensagens FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- 10. HABILITAR REALTIME (Supabase)
-- ============================================================
-- Necessário para que o frontend receba atualizações em tempo real.

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "Pedidos";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "Produtos";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "Usuários";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "Restaurantes";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE mensagens;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ============================================================
-- FIM DO SCRIPT
-- ============================================================
-- Para popular dados de teste, execute:
--
-- INSERT INTO "Restaurantes" (nome, email, senha, quantidade_mesas, quantidade_max_mesas)
-- VALUES ('Restaurante Teste', 'teste@pedeai.com', '123456', '10', '20')
-- ON CONFLICT (email) DO NOTHING;
-- ============================================================
