-- ============================================================
-- PEDEAI — MIGRATION: CRIAÇÃO DA TABELA DE IMPRESSORAS
-- ============================================================
-- Executar no SQL Editor do Dashboard do Supabase
-- ============================================================

-- 1. Criar a tabela de impressoras
CREATE TABLE IF NOT EXISTS "Impressoras" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    "restaurante_id" UUID REFERENCES "Restaurantes"("id") ON DELETE CASCADE,
    "nome" TEXT NOT NULL,
    "tipo" TEXT NOT NULL,          -- 'kitchen' (Cozinha), 'bar' (Bar), 'receipt' (Recibo/Caixa)
    "conexao" TEXT NOT NULL,       -- 'tcp' (Rede IP), 'usb' (USB/COM), 'bluetooth' (Celular), 'browser' (Sistema/PC)
    "ip" TEXT,                     -- IP da impressora de rede (ex: '192.168.1.169')
    "porta" INTEGER DEFAULT 9100,  -- Porta da impressora de rede (ex: 9100)
    "usb_path" TEXT,               -- Caminho USB/Porta COM (ex: '\\.\COM3' ou '\\.\USB001')
    "ativo" BOOLEAN DEFAULT TRUE
);

-- 2. Índices para performance
CREATE INDEX IF NOT EXISTS idx_impressoras_restaurante ON "Impressoras"("restaurante_id");
CREATE INDEX IF NOT EXISTS idx_impressoras_tipo ON "Impressoras"("tipo");
CREATE INDEX IF NOT EXISTS idx_impressoras_ativo ON "Impressoras"("ativo");

-- 3. Habilitar RLS (Row Level Security) e Criar Política de Acesso Livre
ALTER TABLE "Impressoras" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on Impressoras" ON "Impressoras" FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 4. Habilitar Publicações em Tempo Real (Realtime) para o Agente Local ouvir
ALTER TABLE "Impressoras" REPLICA IDENTITY FULL;

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "Impressoras";
EXCEPTION WHEN OTHERS THEN
    -- Ignorar se a publicação não estiver configurada no Supabase local
    NULL;
END $$;
