-- ============================================================
-- PEDEAI — MIGRATION: CRIAÇÃO DA TABELA DE MACARROES
-- ============================================================
-- Executar no SQL Editor do Dashboard do Supabase
-- ============================================================

-- 1. Criar a tabela de macarrões
CREATE TABLE IF NOT EXISTS "Macarroes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    "restaurante_id" UUID REFERENCES "Restaurantes"("id") ON DELETE CASCADE,
    "nome" TEXT NOT NULL,
    "ativo" BOOLEAN DEFAULT TRUE
);

-- 2. Índices para performance
CREATE INDEX IF NOT EXISTS idx_macarroes_restaurante ON "Macarroes"("restaurante_id");
CREATE INDEX IF NOT EXISTS idx_macarroes_ativo ON "Macarroes"("ativo");

-- 3. RLS (Row Level Security)
ALTER TABLE "Macarroes" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on Macarroes" ON "Macarroes" FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 4. Habilitar Realtime
DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "Macarroes";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
