-- ============================================================
-- PEDEAI — MIGRATION: CRIAÇÃO DA TABELA DE SABORES DE PIZZA
-- ============================================================
-- Executar no SQL Editor do Dashboard do Supabase
-- ============================================================

-- 1. Criar a tabela de sabores de pizza
CREATE TABLE IF NOT EXISTS "SaboresPizza" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    "restaurante_id" UUID REFERENCES "Restaurantes"("id") ON DELETE CASCADE,
    "nome" TEXT NOT NULL,
    "preco" TEXT NOT NULL,
    "ativo" BOOLEAN DEFAULT TRUE,
    "descricao" TEXT
);

-- 2. Índices para performance
CREATE INDEX IF NOT EXISTS idx_sabores_restaurante ON "SaboresPizza"("restaurante_id");
CREATE INDEX IF NOT EXISTS idx_sabores_ativo ON "SaboresPizza"("ativo");

-- 3. RLS (Row Level Security)
ALTER TABLE "SaboresPizza" ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on SaboresPizza" ON "SaboresPizza" FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 4. Habilitar Realtime
DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "SaboresPizza";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
