-- ============================================================
-- CRIAÇÃO DE CADASTROS DINÂMICOS: CATEGORIAS E ESTAÇÕES
-- ============================================================

-- 1. TABELA: categorias_restaurante
CREATE TABLE IF NOT EXISTS public.categorias_restaurante (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id UUID NOT NULL REFERENCES public."Restaurantes"(id) ON DELETE CASCADE,
    nome          TEXT NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (restaurante_id, nome)
);

COMMENT ON TABLE public.categorias_restaurante IS 'Categorias de produtos dinâmicas por restaurante';

-- 2. TABELA: estacoes_restaurante
CREATE TABLE IF NOT EXISTS public.estacoes_restaurante (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id UUID NOT NULL REFERENCES public."Restaurantes"(id) ON DELETE CASCADE,
    nome          TEXT NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (restaurante_id, nome)
);

COMMENT ON TABLE public.estacoes_restaurante IS 'Estações de preparo dinâmicas por restaurante';

-- ============================================================
-- 3. SEGURANÇA E RLS (Row Level Security)
-- ============================================================

ALTER TABLE public.categorias_restaurante ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estacoes_restaurante ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Allow all on categorias_restaurante" ON public.categorias_restaurante FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE POLICY "Allow all on estacoes_restaurante" ON public.estacoes_restaurante FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- 4. HABILITAR REALTIME
-- ============================================================

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.categorias_restaurante;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.estacoes_restaurante;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- 5. POPULAR DADOS PADRÃO PARA RESTAURANTES EXISTENTES
-- ============================================================

DO $$
DECLARE
    res_rec RECORD;
    cat_nome TEXT;
    categorias_padrao TEXT[] := ARRAY['Bebida', 'Comida', 'Petisco', 'Porção', 'Sobremesa', 'Lanche', 'Hot Dog', 'Combo', 'Drink', 'Massas', 'Pizza', 'Outros'];
BEGIN
    FOR res_rec IN SELECT id FROM public."Restaurantes" LOOP
        -- Inserir Estações padrão
        INSERT INTO public.estacoes_restaurante (restaurante_id, nome)
        VALUES 
            (res_rec.id, 'Cozinha'),
            (res_rec.id, 'Bar')
        ON CONFLICT (restaurante_id, nome) DO NOTHING;

        -- Inserir Categorias padrão
        FOREACH cat_nome IN ARRAY categorias_padrao LOOP
            INSERT INTO public.categorias_restaurante (restaurante_id, nome)
            VALUES (res_rec.id, cat_nome)
            ON CONFLICT (restaurante_id, nome) DO NOTHING;
        END LOOP;
    END LOOP;
END $$;
